# Generated by Django 2.2.6 on 2020-02-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LitoAngel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='litoangel',
            options={'verbose_name_plural': 'litoangels'},
        ),
    ]
