# Generated by Django 2.2.6 on 2021-07-07 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('describe', models.TextField(blank=True)),
                ('reside', models.CharField(blank=True, max_length=250)),
                ('contact', models.CharField(blank=True, max_length=250)),
                ('watsapp', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Ugconn', max_length=35)),
                ('title', models.CharField(max_length=35)),
                ('about', models.CharField(max_length=35)),
                ('date_as_is', models.DateField()),
                ('site', models.URLField(max_length=300)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('decsription', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='grieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('about', models.CharField(max_length=700)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('describe', models.TextField(blank=True)),
                ('status', models.BooleanField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='OtherActivities', max_length=50)),
                ('activity', models.CharField(max_length=35)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('assign_agent', models.CharField(blank=True, max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='investmoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='investmoney', max_length=50)),
                ('title', models.CharField(max_length=35)),
                ('activity', models.CharField(max_length=35)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='feesandbills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='FeesAndBills', max_length=50)),
                ('activity', models.CharField(max_length=35)),
                ('amount', models.CharField(max_length=35)),
                ('payplan', models.FileField(upload_to='plans')),
                ('receiver', models.CharField(max_length=35)),
                ('receiver_contact', models.CharField(default='', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('assign_agent', models.CharField(blank=True, max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='donatemoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DonateMoney', max_length=50)),
                ('orgname', models.CharField(max_length=35)),
                ('activity', models.CharField(max_length=35)),
                ('reside', models.CharField(max_length=35)),
                ('contact', models.CharField(max_length=35)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('assign_agent', models.CharField(blank=True, max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='clientprofiles/')),
                ('contact', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(max_length=15)),
                ('facebook', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('parentDeck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='buyland',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BuyLand', max_length=50)),
                ('reside', models.CharField(max_length=35)),
                ('structure', models.CharField(max_length=35)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('assign_agent', models.CharField(blank=True, max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='buyitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BuyItems', max_length=50)),
                ('item', models.CharField(max_length=35)),
                ('quantity', models.CharField(max_length=35)),
                ('quality', models.CharField(max_length=35)),
                ('receiver', models.CharField(max_length=35)),
                ('contact', models.CharField(max_length=35)),
                ('reside', models.CharField(max_length=35)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('assign_agent', models.CharField(blank=True, max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='buyhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BuyHouse', max_length=50)),
                ('reside', models.CharField(max_length=35)),
                ('structure', models.CharField(max_length=35)),
                ('serviceprovider', models.CharField(max_length=35)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('assign_agent', models.CharField(blank=True, max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='buildhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Buildhouse', max_length=50)),
                ('reside', models.CharField(max_length=35)),
                ('structure', models.CharField(max_length=35)),
                ('serviceprovider', models.CharField(max_length=35)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('assign_agent', models.CharField(blank=True, max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
