# Generated by Django 2.2.6 on 2021-07-07 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('amount', models.IntegerField(default=0)),
                ('remain', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('timezone', models.CharField(max_length=36)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('agent_status', models.BooleanField(default=False)),
                ('client_status', models.BooleanField(default=False)),
                ('timer', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateTimeField(blank=True)),
                ('activity', models.CharField(max_length=45)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('body', models.TextField()),
                ('agent_status', models.BooleanField(default=False)),
                ('client_status', models.BooleanField(default=False)),
                ('timer', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('comments', models.ManyToManyField(to='kunai.comment')),
            ],
        ),
        migrations.CreateModel(
            name='youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('describe', models.TextField(blank=True)),
                ('url_channel', models.URLField()),
                ('timer', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True)),
                ('client', models.CharField(max_length=45)),
                ('agent', models.CharField(max_length=45)),
                ('agent_notes', models.TextField()),
                ('estimated_time', models.CharField(max_length=10)),
                ('meeting_type', models.CharField(max_length=20)),
                ('next_meeting', models.DateTimeField()),
                ('meeting_const', models.BooleanField(default=False)),
                ('activity_docs', models.FileField(blank=True, upload_to='projectDocs/')),
                ('google_doc', models.URLField(blank=True)),
                ('budget_timeline', models.ManyToManyField(to='kunai.bank')),
                ('media', models.ManyToManyField(to='kunai.youtube')),
                ('notes', models.ManyToManyField(to='kunai.notes')),
                ('previous_meeting', models.ManyToManyField(to='kunai.meeting')),
                ('timeline', models.ManyToManyField(to='kunai.history')),
            ],
        ),
    ]
