# Generated by Django 2.2.6 on 2021-07-10 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kunai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='comments',
            field=models.ManyToManyField(blank=True, to='kunai.comment'),
        ),
    ]
