# Generated by Django 2.2.6 on 2021-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunai', '0002_auto_20210710_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timer',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='timer',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='timer',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
