# Generated by Django 2.2.6 on 2019-12-29 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='buildhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reside', models.CharField(max_length=35)),
                ('structure', models.CharField(max_length=35)),
                ('serviceprovider', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=35)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.users')),
            ],
        ),
    ]
