# Generated by Django 2.2.6 on 2019-12-29 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_buildhouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildhouse',
            name='description',
        ),
        migrations.AddField(
            model_name='buildhouse',
            name='brief',
            field=models.CharField(default=django.utils.timezone.now, max_length=700),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=35)),
                ('notes', models.CharField(max_length=700)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.users')),
            ],
        ),
        migrations.CreateModel(
            name='investmoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('activity', models.CharField(max_length=35)),
                ('notes', models.CharField(max_length=700)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.users')),
            ],
        ),
        migrations.CreateModel(
            name='feesandbills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=35)),
                ('amount', models.CharField(max_length=35)),
                ('receiver', models.CharField(max_length=35)),
                ('notes', models.CharField(max_length=700)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.users')),
            ],
        ),
        migrations.CreateModel(
            name='donatemoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=35)),
                ('activity', models.CharField(max_length=35)),
                ('reside', models.CharField(max_length=35)),
                ('notes', models.CharField(max_length=700)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.users')),
            ],
        ),
        migrations.CreateModel(
            name='buyland',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reside', models.CharField(max_length=35)),
                ('structure', models.CharField(max_length=35)),
                ('notes', models.CharField(max_length=700)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.users')),
            ],
        ),
        migrations.CreateModel(
            name='buyitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=35)),
                ('quantity', models.CharField(max_length=35)),
                ('quality', models.CharField(max_length=35)),
                ('receiver', models.CharField(max_length=35)),
                ('contact', models.CharField(max_length=35)),
                ('reside', models.CharField(max_length=35)),
                ('notes', models.CharField(max_length=700)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.users')),
            ],
        ),
        migrations.CreateModel(
            name='buyhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reside', models.CharField(max_length=35)),
                ('structure', models.CharField(max_length=35)),
                ('serviceprovider', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=700)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.users')),
            ],
        ),
    ]
