# Generated by Django 2.2.6 on 2019-12-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20191229_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildhouse',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
