# Generated by Django 2.2.6 on 2020-01-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_auto_20191229_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='grieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('about', models.CharField(max_length=700)),
                ('notes', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.users')),
            ],
        ),
    ]
