# Generated by Django 2.2.6 on 2020-01-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_grieve'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('about', models.CharField(max_length=35)),
                ('date_as_is', models.DateField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='grieve',
            name='username',
        ),
    ]
