# Generated by Django 2.2.6 on 2020-02-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0010_auto_20200207_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
