# Generated by Django 2.2.6 on 2020-02-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatemoney',
            name='contact',
            field=models.CharField(default=11, max_length=35),
            preserve_default=False,
        ),
    ]
