# Generated by Django 2.2.6 on 2020-02-10 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_donatemoney_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesandbills',
            name='payplan',
            field=models.FileField(default=django.utils.timezone.now, upload_to='plans'),
            preserve_default=False,
        ),
    ]
