# Generated by Django 2.2.6 on 2020-02-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0013_feesandbills_payplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Ugconn', max_length=35),
        ),
    ]
