# Generated by Django 2.2.6 on 2020-02-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0014_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.URLField(default='www.google.com', max_length=300),
            preserve_default=False,
        ),
    ]
