# Generated by Django 2.2.6 on 2020-08-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0016_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='contact',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='about',
            name='reside',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='about',
            name='watsapp',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
