# Generated by Django 2.2.6 on 2020-12-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0017_auto_20200811_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('describe', models.TextField(blank=True)),
                ('status', models.BooleanField()),
                ('link', models.URLField()),
            ],
        ),
    ]
